version: '3.6'

services:
  backupfriend:
    image: guysoft/backupfriend
    container_name: backupfriend
    restart: always
    volumes:
      - "${BACKUP_PATH}:/backup"
      - "${MEDIA_PATH}:/media"
      - "${DB_PATH}:/etc/rdiffweb/rdw.db"
      - "${USER_KEYS_PATH}:/etc/authorized_keys/user"
      - "${RDW_CONF}:/etc/rdiffweb/rdw.conf"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      # - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    tty: true
    privileged: true
    entrypoint: rdiffweb
    ports:
      - "${EXTRA_PORT}:8080"
  sshd:
    image: guysoft/backupfriend-ssh
    container_name: backupfriend-sshd
    restart: always
    volumes:
      - "${BACKUP_PATH}:/backup"
      - "${MEDIA_PATH}:/media"
      - "${USER_KEYS_PATH}:/etc/authorized_keys/user"
    tty: true
    ports:
      - "${SSH_PORT}:22"
    environment:
      - SSH_USERS=user:1000:1000

networks:
  default:
    external:
      name: nginx-proxy

