version: '3.6'

services:
  backupfriend:
    image: guysoft/backupfriend
    container_name: backupfriend
    restart: always
    volumes:
      - "/backup:/backup"
      - "/etc/rdiffweb/rdw.db:/etc/rdiffweb/rdw.db"
      - "/etc/authorized_keys/user:/etc/authorized_keys/user"
      - "./rdw.conf:/etc/rdiffweb/rdw.conf"
    environment:
      - VIRTUAL_HOST=backupfriend,backupfriend.local
      - VIRTUAL_PORT=8080
      # - LETSENCRYPT_EMAIL=user@foo.bar.com
      # - LETSENCRYPT_HOST=backupfriend.domain
    tty: true
    privileged: true
    entrypoint: rdiffweb
    ports:
      - "8082:8080"
  sshd:
    image: guysoft/backupfriend-ssh
    container_name: backupfriend-sshd
    restart: always
    volumes:
      - "/backup:/backup"
      - "/etc/authorized_keys/user:/etc/authorized_keys/user"
    tty: true
    ports:
      - "8022:22"
    environment:
      - SSH_USERS=user:1000:1000

networks:
  default:
    external:
      name: nginx-proxy

